### ISSUE TITLE
Change setup.py "description" to "Python one-liners in the spirit of Perl and AWK."

### ISSUE THREAD

**Issue by SethMMorton** [ninjaaron/pyfil#1]
The current description, "print the return value of python expression -- also in loops", does not do the project justice nor capture the most exciting features of the project. My initial thought based on this description was that this project was a pretty-printer.

The line "Python one-liners in the spirit of Perl and AWK." from the README does a much better job of setting a potential user's expectations.  Perhaps an even more descriptive line would be "Python-language one-liners in the shell, in the spirit of Perl and AWK."?

**Comment by ninjaaron** [comment]
Great idea!

**Comment by petonic** [comment]
Not appropriate here, but wanted to give a quick thank you for having released this well-designed utility.  It's really helpful in doing lots of things on the CLI, including managing docker containers and images.  Much appreciated, Aaron!

**Comment by ninjaaron** [comment]
@petonic Glad to hear you like it! It's always hard to know how many people are really using your projects, and I'm happy that others are using this one. I have some other projects which are more popular (by github metrics), but this is the one I personally think is the coolest, so I really appreciate the positive feedback.

In terms of design, I can't take much credit.

- Most of the ideas are from Perl and AWK. If I did anything right, it was recognizing what makes these languages so awesome for oneliners.
- Automatic imports was stolen from another Python oneliner project (not sure which one at the moment... It was two years ago.)
- It became JSON-centric because someone in the #python IRC said "I'll use it if I can parse JSON with it." Printing JSON instead of Python literals was my idea, but I never would have thought of it if someone else hadn't gotten me thinking about JSON interop in the first place.

**Comment by petonic** [comment]
As they say, it takes a village. 

I saw the auto imports from another util. Snarfing the best ideas, of course. I’m glad that you continue to actively maintain it.
