### ISSUE TITLE
Automatically import objects from modules using importmagic

### ISSUE THREAD

**Issue by rominf** [ninjaaron/pyfil#2]
Let's assume I want to calculate something using pyfil. Now I have to write:
```shell
$ pyfil 'math.sin(math.pi)'
```

Let's agree, it's a little bit wordy, hard readable and hard to type.

I wish I could write it like this:
```shell
$ pyfil 'sin(pi)'
```

It's not hard to achieve at all. There is a nice library [importmagic](https://github.com/alecthomas/importmagic) that does automatic imports. The only thing that is left is to integrate it. And, if understand it correctly, this will give you the ability to simplify the code by getting rid of namespaces.

What do you think of this feature?

PS: Thank you for pyfil. It's cool!

**Comment by ninjaaron** [comment]
Thanks for your interest in pyfil! I'm happy people use it.

Unfortunately, I'm not going to be adding any functionality that will implicitly put every name in sys.path into the default namespace. There would be too many collisions and the wrong names would certainly get masked for some people. Implicitly allowing all modules to be imported is already questionable enough!

However, there is a feature which you may personally use to modify the default namespace. You can create a file, `~/.config/pyfil-env.py`, and import anything there. (as well as do any other setup steps you might like)

~/.config/pyfil-env.py:
```python
from math import *
```
In the shell:
```bash
$ pyfil 'sin(pi)'
1.2246467991473532e-16
```
This allows each user to specify their own execution environment without having to worry about namespace collisions. What do you think?

**Comment by rominf** [comment]
Thank you for proposing `~/.config/pyfil-env.py`, but I want a solution with minimal difficulties for the user.

I understand your concerns.

About names masking: by default namespace is almost empty. If the user wants to define the variable `sin` he will do:
```shell
 $ pyfil -b 'sin = True' 'sin'
```
No auto imports will be involved as the variable is already defined.

About collisions: that's true that collisions can occur. But on the other hand, I'm sure that most of the times user will get what he wants. He will just execute the pyfil and see whether he gets a correct result or not. If not, he can always import explicitly:
```shell
$ pyfil -b 'from math import sin' 'sin'
```

What do you think about my arguments?

**Comment by ninjaaron** [comment]
I think the default namespace isn't "almost empty". Aside from the 69 built-in functions, every module in `sys.path` can be implicitly imported. This namespace is already beginning to become crowded. You're right, of course, that names can be redefined if necessary.

Consider the following:
```python
>>> import math                                                                                                                                                              
>>> import numpy as np                                                                                                                                                       
>>> mathsym = set(dir(math))                                                                                                                                                 
>>> npsym = set(dir(np))                                                                                                                                                     
>>> mathsym & npsym                                                                                                                                                          
{'sqrt', 'remainder', 'expm1', 'ceil', 'nan', 'inf', 'fmod', 'cosh', 'exp', 'copysign', 'cos', 'tanh', 'e', 'trunc', 'sinh', 'ldexp', 'tan', 'degrees', 'pi', 'modf', 'floor', 'log', '__spec__', '__name__', 'frexp', 'isclose', 'isnan', '__package__', 'hypot', 'isinf', 'isfinite', 'sin', '__doc__', 'fabs', '__file__', '__loader__', 'log1p', 'gcd', 'radians', 'log2', 'log10'}
>>> len(_)
41
```
That's 41 overlapping names just in these two modules. You may argue that most of these names have similar functionality. Well, Let's try another:

```python
>>> import typing                                                                                                                                                            
>>> from collections import abc                                                                                                                                              
>>> typing = set(dir(typing))                                                                                                                                                
>>> abc = set(dir(abc))                                                                                                                                                      
>>> typing & abc                                                                                                                                                             
{'Mapping', 'ValuesView', 'AsyncIterator', 'Generator', 'Iterable', 'MappingView', 'MutableSequence', 'AsyncGenerator', 'MutableMapping', 'ByteString', 'AsyncIterable', '__cached__', 'Set', 'Sized', '__spec__', '__name__', '__builtins__', 'Collection', 'MutableSet', '__package__', 'Container', 'Iterator', 'KeysView', '__doc__', 'ItemsView', 'Sequence', '__file__', 'Awaitable', '__loader__', 'Callable', 'Coroutine', 'Hashable', 'Reversible', '__all__'}
>>> len(_)                                                                                                                                                                   
34
```
34 overlapping names, and these aren't different version of the same thing. I think what you're asking for is too unpredictable. We're talking about tens of thousands of names here. While typing the line `echo "from math import *" >> ~/.config/pyfil-env.py` may seem unbearable to someone who is annoyed by having to type `math.sin(math.pi)`, it is ultimately a much better solution because it gives the user control over exactly which names are being imported without any of this namespace roulette.

There are other concerns.

- performance: Building an index of all names in sys.path is no mean task, and not something you generally want to think about when running shell oneliners.
- complexity: pyfil is currently a single file of < 400 lines (including comments and whitespace). importmagic is a package with 11 modules, and over half of them are longer than pyfil in its entirety. Taking on a dependency like that for a project that currently only needs the standard library would make me think twice even if I didn't think this was unwise for other reasons. If it were a major library like Requests that everyone already uses, that might be fine, but this is different.

If and only if I get bored or interested, I may play with adding -i/--importmagic flag so you can experience the namespace hell you so desire, but that's not a promise. This is not going on the TODO list, it's just something sitting in the back of my mind.

**Comment by rominf** [comment]
OK, I understand your reasoning. I have to admit that it's strong and using importmagic should be optional only.

So, if I get bored or interested too, I will try to make PR. But that's not a promise too, because, I have to admit, I found pyfil code little bit complicated. But probably that's because of pyfil is powerful.

PS: I want "namespace hell" because I think that if you write oneliners, they should be as short as possible and should not require to modify environment.

**Comment by ninjaaron** [comment]
The code could do with some cleanup. I started the project some years ago when I had significantly less experience at writing modular code, and there are a lot of improvements that could be made to the design that would improve readability. *That* is definitely something that should be on the roadmap.

**Comment by rominf** [comment]
And yes, my first suggestion was to search through all exported objects of all libraries on PyPI (sorting them by popularity) and install the library automatically. Of course, I wanted to build an index at server-side and download it by request.

But even I decided that that's too much :)
