### ISSUE TITLE
Allow import statements

### ISSUE THREAD

**Issue by rominf** [ninjaaron/pyfil#3]
In #2 I proposed to automatically import objects from modules to achieve this:
```shell
$ pyfil 'sin(pi)'
```
instead of:
```shell
$ pyfil 'math.sin(math.pi)'
```

There is another solution to get rid of the `math` module in code, just allow to do import statements:
```shell
$ pyfil 'from math import sin, pi' 'sin(pi)'
```
What do you think of this feature?

**Comment by ninjaaron** [comment]
I think it's already possible!

```bash
$ pyfil -b 'from math import *' 'sin(pi)'
1.2246467991473532e-16
```
The the reason the `-b` or `--pre` flag is needed is the difference between statements and expressions in Python, and the difference between `exec` and `eval`. The `eval` function only takes expressions and returns their value. `exec` will run arbitrary code (including statements), but returns `None`. Because pyfil is mostly about printing values to stdout, `eval` is used in the common case.

`import` syntax is a _statement_, not an _expression_. It doesn't evaluate to a value, and therefore cannot be used with `eval`. However, there are two ways to get pyfil to use `exec`: The first is to use the `-x` / `--exec` flag. This sends all arguments to pyfil into `exec`. The result, however, is that no value is printed. Printing must be explicit with the print function.

The other alternative, shown above, is to use the `-b` /  `--pre` flag, which is a line of code which will be run with `exec` before all the following expressions are evaluated. One can use this for imports or assignment or anything. Use semi-colons where appropriate, i.e. `pyfil -b 'from math import *; s = set(); foo = "bar"`, etc.

Is this functionality sufficient?

**Comment by rominf** [comment]
Yes, this functionality is sufficient. I didn't read the documentation carefully enough. Sorry.

About _statements_ and _expressions_: my bad, I mixed up again. You are right.

Thank you for your answer!
